version: "3"

services:
  rest_api:
    container_name: rest_api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.prod
    environment:
      - NEXT_PUBLIC_ENVIRONMENT=${ENVIRONMENT}
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
      - NEXT_PUBLIC_SENTRY_DISABLED=${SENTRY_DISABLED}
