version: "3"

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80

  rest_api:
    container_name: rest_api
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env.production

  web:
    env_file:
      - .env.production
