name: publish

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api Docker Image
        id: api_deploy
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ghcr.io/${{github.repository}}/api:${{github.sha}}

      - name: Build and push web Docker Image
        id: web_deploy
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ghcr.io/${{github.repository}}/web:${{github.sha}}
          build-args: |
            NEXT_PUBLIC_API_PATH=${{SECRETS.NEXT_PUBLIC_API_PATH}}
            SENTRY_AUTH_TOKEN=${{SECRETS.SENTRY_AUTH_TOKEN}}
            NEXT_PUBLIC_TEST=${{SECRETS.NEXT_PUBLIC_TEST}}

      - name: Trigger dokku deployment
        uses: appleboy/ssh-action@master
        with:
          host: 143.198.146.197
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          debug: true
          script: |
            dokku git:from-image api ghcr.io/${{github.repository}}/api:${{github.sha}}
            dokku git:from-image web ghcr.io/${{github.repository}}/web:${{github.sha}}

      - name: Delete old api images
        uses: actions/delete-package-versions@v2
        with:
          package-name: "api"
          token: ${{secrets.GITHUB_TOKEN}}
          min-versions-to-keep: 3

      - name: Delete old web images
        uses: actions/delete-package-versions@v2
        with:
          package-name: "web"
          token: ${{secrets.GITHUB_TOKEN}}
          min-versions-to-keep: 3
