name: E2E Testing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to container registry
      run: |
        docker build . --tag ghcr.io/jonashackt/hello-docker:latest
        docker run ghcr.io/jonashackt/hello-docker:latest
        docker push ghcr.io/jonashackt/hello-docker:latest
