name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the api Docker image
        env:
          DATABASE_URL: postgres://yourUser:changeit@postgres:5432/prisma?schema=hello-prisma
        run: |
          cd api
          docker build . --tag ghcr.io/doggo-sports/api:latest
          docker push ghcr.io/doggo-sports/api:latest

      - name: Build the web Docker image
        env:
          TEST: i am just a little testerman
          SENTRY_AUTH_TOKEN: ${{SECRETS.SENTRY_AUTH_TOKEN}}
        run: |
          cd web
          docker build . --tag ghcr.io/doggo-sports/web:latest
          docker push ghcr.io/doggo-sports/web:latest

      - name: Sentry Release
        uses: getsentry/action-release@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
