name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push api Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ghcr.io/${{github.actor}}/api:latest

      - name: Build and push web Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ghcr.io/d${{github.actor}}/web:latest
          build-args: |
            NEXT_PUBLIC_API_PATH=${{SECRETS.NEXT_PUBLIC_API_PATH}}
            SENTRY_AUTH_TOKEN=${{SECRETS.SENTRY_AUTH_TOKEN}}
            NEXT_PUBLIC_TEST=${{SECRETS.NEXT_PUBLIC_TEST}}

      # - name: Build the api Docker image
      #   env:
      #     DATABASE_URL: postgres://yourUser:changeit@postgres:5432/prisma?schema=hello-prisma
      #   run: |
      #     cd api
      #     docker build . --tag ghcr.io/doggo-sports/api:latest
      #     docker push ghcr.io/doggo-sports/api:latest
      #     echo "API_IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/doggo-sports/api:latest)" >> $GITHUB_ENV \

      # - name: Build the web Docker image
      #   env:
      #     SENTRY_AUTH_TOKEN: ${{SECRETS.SENTRY_AUTH_TOKEN}}
      #   run: |
      #     cd web
      #     docker build \
      #       --build-arg NEXT_PUBLIC_API_PATH="${{SECRETS.NEXT_PUBLIC_API_PATH}}" \
      #       --build-arg SENTRY_AUTH_TOKEN="${{SECRETS.SENTRY_AUTH_TOKEN}}" \
      #       --build-arg NEXT_PUBLIC_TEST="${{SECRETS.NEXT_PUBLIC_TEST}}" \
      #       . --tag ghcr.io/doggo-sports/web:latest
      #       docker push ghcr.io/doggo-sports/web:latest
      #       echo "WEB_IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.io/doggo-sports/web:latest)" >> $GITHUB_ENV

      # - name: Trigger dokku deployment
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: 143.198.146.197
      #     username: ${{secrets.DOKKU_SSH_USER}}
      #     password: ${{secrets.DOKKU_SSH_USER_PASSWORD}}
      #     key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       dokku git:from-image api ${{ env.API_IMAGE_DIGEST }}
      #       dokku git:from-image web ${{ env.WEB_IMAGE_DIGEST }}
