name: publish

on: [push]

jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the api Docker image
        env:
          DATABASE_URL: postgres://yourUser:changeit@postgres:5432/prisma?schema=hello-prisma
        run: |
          cd api
          docker build . --tag ghcr.io/doggo-sports/api:latest
          docker push ghcr.io/doggo-sports/api:latest

      - name: Build the web Docker image
        env:
          SENTRY_AUTH_TOKEN: ${{SECRETS.SENTRY_AUTH_TOKEN}}
        run: |
          cd web
          docker build \
            --build-arg NEXT_PUBLIC_API_PATH="${{SECRETS.NEXT_PUBLIC_API_PATH}}" \
            --build-arg SENTRY_AUTH_TOKEN="${{SECRETS.SENTRY_AUTH_TOKEN}}" \
            --build-arg NEXT_PUBLIC_TEST="${{SECRETS.NEXT_PUBLIC_TEST}}" \
            . --tag ghcr.io/doggo-sports/web:latest
          docker push ghcr.io/doggo-sports/web:latest

      - name: Get SHA's for new images
        run: |
        echo "API_IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.com/user/api:latest)" >> $GITHUB_ENV
        echo "WEB_IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ghcr.com/user/web:latest)" >> $GITHUB_ENV

      - name: Trigger dokku deployment
        uses: appleboy/ssh-action@master
        with:
          host: 143.198.146.197
          username: anthony
          key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            dokku git:from-image web ${{ env.IMAGE_DIGEST_WEB }}