name: Deploy Testing Environment and run E2E

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push api testing image
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: ghcr.io/${{github.repository}}/api:${{github.sha}}

      - name: Build and push web testing image
        uses: docker/build-push-action@v2
        with:
          context: ./web
          push: true
          tags: ghcr.io/${{github.repository}}/web:${{github.sha}}
          build-args: |
            NEXT_PUBLIC_API_PATH=${{secrets.NEXT_PUBLIC_API_PATH}}
            SENTRY_AUTH_TOKEN=${{secrets.SENTRY_AUTH_TOKEN}}
            NEXT_PUBLIC_TEST=${{secrets.NEXT_PUBLIC_TEST}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger api testing deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
            dokku git:from-image test-api ghcr.io/${{github.repository}}/api:${{github.sha}}

      - name: Trigger web testing deployment to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.DOKKU_HOST}}
          username: ${{secrets.DOKKU_SSH_USER}}
          key: "${{ secrets.DOKKU_SSH_PRIVATE_KEY }}"
          script: |
            dokku git:from-image test-web ghcr.io/${{github.repository}}/web:${{github.sha}}

  e2e:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run Cypress E2E Tests
        run: npm run cypress:run

      # Just could not get these to work.
      # - name: Delete old api images
      #   uses: actions/delete-package-versions@v2
      #   with:
      #     package-name: "api"
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     min-versions-to-keep: 3

      # - name: Delete old web images
      #   uses: actions/delete-package-versions@v2
      #   with:
      #     package-name: "web"
      #     token: ${{secrets.GITHUB_TOKEN}}
      #     min-versions-to-keep: 3
